module.exports = {
    sverchok: {
        state: "active",
        title: "Сказка о семейном счастье, или Сверчок за очагом",
        author: "Чарльз Диккенс",
        imgHolder: "holder.js/900x500/auto/#777:#7a7a7a/text:First slide",
        imgCover: require("../program/sverchok/img/cover.jpg"),
        schedule: "все даты на текущий месяц и следующий",
        time: "Начало в 19:00",
        awards: "Лауреат международного фестиваля “Твой Шанс”, Москва.<br />Лучший спектакль сезона 2015/16 Учебного театра на Моховой, Санкт-Петербург.",
        content: "Эта светлая история по сюжету Чарльза Диккенса напоминает нам о самых важных вещах, которые вовсе и не вещи. А потому так хрупки и так важны для каждого. Домашний уют, понимание, уважение и любовь, теплота и забота... <br /> Все эти “бесценности” в наших домах оберегают невидимые Хранители - Духи дома и верные друзья хозяев: <br /> Дух зеркала заботливо оберегает красоту милой хозяйки, <br /> Дух огня готовит горячий чай, <br /> Дух порядка ворчит, если одежда небрежно кинута на вешалку...<br /> А еще в любом доме живут Дух часов, Дух света и даже Дух игрушек! <br /> Но смогут ли Хранители уберечь семейное счастье, когда в доме вдруг появится странный непрошеный гость?",
        premier: "14/11/2015",
        director: "Наталья Лапина",
        restrictions: "+12",
    },
    nepostoyanstvo: {
        title: "Двойное <br/>непостоянство",
        author: "Пьер Карле де Шамблен де Мариво",
        imgHolder: "holder.js/900x500/auto/#666:#6a6a6a/text:Second slide",
        imgCover: require("../program/nepostoyanstvo/img/cover.jpg"),
        time: "Начало в 19:00",
        awards: "aaaaaaaaaa",
        content: "aaaaaaaaa",
        premier: "14/11/2015",
        director: "Наталья Лапина",
        restrictions: "+12",
    },
    wolf: {
        title: "Хочу быть волком",
        author: "Беттина Вегенаст",
        imgHolder: "holder.js/900x500/auto/#555:#5a5a5a/text:Third slide",
        imgCover: require("../program/wolf/img/cover.jpg"),
    },
    belyenochi: {
        title: "Белые ночи",
        author: "Ф.М. Достоевский",
        imgHolder: "holder.js/900x500/auto/#555:#5a5a5a/text:Third slide",
        imgCover: require("../program/belyenochi/img/cover.jpg"),
    },
    derevnya: {
        title: "Месяц в деревне",
        author: "И.С.Тургенев",
        imgHolder: "holder.js/900x500/auto/#555:#5a5a5a/text:Third slide",
        imgCover: require("../program/derevnya/img/cover.jpg"),
    },
}